modLoader = "javafml"
loaderVersion = "[40,41)"
license = "MIT"
issueTrackerURL = "https://github.com/der-fruhling-entertainment/create-train-perspective/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Create: Train Perspective"
updateJSONURL = "https://api.modrinth.com/updates/create-train-perspective/forge_updates.json"
displayURL = "https://modrinth.com/mod/create-train-perspective"
logoFile = "create_train_perspective.png"
#credits="Thanks for this example mod goes to Java"
authors = "der_frühling"
displayTest = "IGNORE_ALL_VERSION"

description = '''
Moves your camera (and body!) with the Create Mod train you're riding to increase immersion!
'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[40,41)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "1.18.2"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange = "[0.5.0,0.6.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
mandatory = true
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "cloth_config"
mandatory = false
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"
